### ISSUE TITLE
文档需要简洁一下

### ISSUE THREAD

**Issue by wukaiying** [hunterhug/taobaoscrapy#2]
大哥文档能不能优化一下，看了半天啊。
<img width="647" alt="image" src="https://user-images.githubusercontent.com/7676297/28916903-531bef92-7876-11e7-848a-20436f9071cf.png">

**Comment by hunterhug** [comment]
build好有完整插件的的image，image都完整了为什么还要build？没看懂，并不代表有问题。

这并不是废话，假设中间去掉任何指导，你会更糊涂。对于不懂docker的同学，我写了另外本地安装的指导，你可以参考。不需要在issues发这种莫名其妙没什么营养的提问，你可以fork到自己的本地，然后觉得哪里有问题，你可以修改，然后给我提PR。

这个小工具是面对小白用户的，所以文档已经够长了。对于会使用Python的开发者，只要学会了基本语法的，不需要啥文档，安装好环境和一些库直接python *.py就可以跑了。

关于docker，因为本人是做云计算的，觉得在Linux下装环境比较麻烦，引导以下初学者可以去了解一下新的工具。

你可以Pull一个python的镜像来跑，然后将项目挂载进容器（中间那部分教你如何将这个项目的源码挂进docker容器里）。你可以选择运行前pip install，但是这样很慢，(解释除了python环境你还需要一些库，自己在本地build，这样在拉镜像的同时会帮你pip，并持久在你的机器上)，所以我建议不要用pull的方式，而是在本地build。我的Dockerfile已经写好了，你可以看到的内容是：

```
FROM python:3.5.2
MAINTAINER 569929309@11.com
RUN pip3 install pymysql
RUN pip3 install xlsxwriter
RUN pip3 install bs4
RUN pip3 install openpyxl
RUN pip3 install Pillow
```

你可以理解吧？
